[build]
  command = "pip install -r requirements.txt && netlify-lambda build functions"
  functions = "netlify/functions"
  publish = "templates"

[[redirects]]
  from = "/*"
  to = "/app"
  status = 200